### ISSUE TITLE
multiple downloads

### ISSUE THREAD

**Issue by Gamegod4** [Goobwabber/MultiplayerAvatars#7]
me and a group were playing 4.3 multi with beat together. we have issues seeing each others models. some show some dont. then some eventally work or break. and we are constantly downloading each others models. im up to 30 of one persons avatar. ive recently been playing 4.3 so this is the first time ive seen it work at all

**Comment by Cyasi** [comment]
Having the same issue. Tried 3 sorts of Avatars:
-The First was a custom Avatar, which was working perfectly in singleplayer. in multiplayer it fell back to the normal beatsaber avatar.
-The second one was the normal Template Avatar; invisible to the other player (no fallback, there was nothing but digital air).
-The third one was downloaded (https://modelsaber.com/Avatars/?id=1561892950&pc). Also invisible for the other but this time he constantly downloaded it. we were only talking in the lobby for one minute and he had the avatar 24 times downloaded.

No avatars worked for us, not even the default template.

Log: [_latest.log](https://github.com/Goobwabber/MultiplayerAvatars/files/6098102/_latest.log)

Beatsaber is up to date, got the requirements. only sirautil is version 2.5.1 instead of 2.4.0.

**Comment by LucaFox** [comment]
I'll be working on a fix for the multiple downloads today. I already see the problem and it should be a pretty straightforward fix.
I'll update the dependencies and game version in the process.

You can delete all the duplicate avatars once it's ready.

@Cyasi Thanks for the logs, it certainly helps identify issues. From what I can tell, you're always receiving an 'FFFFFFFF' hash from the avatar packet in multiplayer. i.e. 'no avatar set'. Hence why you're seeing the base avatar. Your friends /logs/MultiplayerAvatars/_latest.log may provide more detail.

As for Custom avatars not on beatmods.com, it will only work if you both have the same .avatar file in your customavatars folder. 
It does not seem wise to have the mod download avatar files directly from the other user's system. MAYBE later on we could add a 'trust other players' toggle to allow it, but I'd like to see the mod work consistently before I do anything clever with it. I'll add it to the 'known issues' in the readme for now.

**Comment by LucaFox** [comment]
Update:
The [Latest Build](https://github.com/Goobwabber/MultiplayerAvatars/actions/runs/632352546) should work.
I just tested it locally, and assuming both parties have their mods up to date, it's good to go.

**Comment by Cyasi** [comment]
@LucaFox it works now, thank you! Even with my Custom Avatar, and thank you for the explanation!
One question: Is fullbodytracking not supported? My Friend cannot see me moving legs and hip (and suddenly I have problems with my waist tracker now, which I didn't had yesterday)? Dont know if this was working before.
